# Generated by Django 3.0.6 on 2020-05-25 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('start_date', models.DateField()),
                ('milk_men', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.MilkMan')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Rate'),
        ),
    ]
