# Generated by Django 3.0.6 on 2020-05-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_auto_20200525_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='milk_men',
            new_name='milk_man',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='milk_men',
            new_name='milk_man',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='milk_men',
            new_name='milk_man',
        ),
    ]
