# Generated by Django 3.0.6 on 2020-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0004_auto_20200525_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
