# Generated by Django 3.0.6 on 2020-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0005_auto_20200525_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
