# Generated by Django 3.0.6 on 2020-05-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0006_auto_20200525_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MilkMan',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='milk_man',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='milk_man',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='milk_man',
            new_name='supplier',
        ),
    ]
