# Generated by Django 3.0.6 on 2020-05-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rent', models.FloatField()),
                ('rent_type', models.CharField(default='A', max_length=1)),
                ('rent_date', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment', models.FloatField()),
                ('status', models.BooleanField()),
                ('remarks', models.CharField(default='', max_length=500)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.Room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.Tenant')),
            ],
        ),
    ]
