# Generated by Django 3.0.6 on 2020-05-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_auto_20200522_2317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propery',
            new_name='Property',
        ),
    ]
