# Generated by Django 3.0.6 on 2020-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_auto_20200523_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupency',
            old_name='rent',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='occupency',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='occupency',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='occupency',
            name='rent_month',
        ),
        migrations.RemoveField(
            model_name='occupency',
            name='status',
        ),
        migrations.AlterField(
            model_name='occupency',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
