# Generated by Django 3.0.6 on 2020-05-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_auto_20200523_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupency',
            name='start_date',
            field=models.DateField(),
        ),
    ]
