# Generated by Django 3.0.6 on 2020-05-23 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_auto_20200523_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupency',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.DateField()),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('occupency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.Occupency')),
            ],
        ),
    ]
