# Generated by Django 3.0.6 on 2020-05-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_auto_20200523_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='remarks',
            new_name='remark',
        ),
    ]
